"""Regenerate docs/features.md from what tsfresh and TSFEL actually emit.

    uv run python scripts/gen_feature_docs.py

Every tsfresh calculator and TSFEL feature is listed with an example column
name and the tsrocket name it parses to, so the page can't drift from the code.
"""

import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import tsfel
from tsfresh import extract_features
from tsfresh.feature_extraction import ComprehensiveFCParameters

import tsrocket

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tests"))
from references import NO_REFERENCE  # noqa: E402

warnings.filterwarnings("ignore")


def canonical(names, **kwargs):
    return tsrocket.Extractor(list(names), **kwargs).feature_names


def tsfresh_rows(x):
    df = pd.DataFrame({"id": 0, "time": np.arange(len(x)), "value": x})
    cols = extract_features(
        df,
        column_id="id",
        column_sort="time",
        default_fc_parameters=ComprehensiveFCParameters(),
        disable_progressbar=True,
        n_jobs=0,
    ).columns
    first = {}
    for col in cols:
        first.setdefault(col.split("__")[1], col)
    return [(calc, col, name) for (calc, col), name in zip(first.items(), canonical(first.values()))]


def tsfel_rows(x):
    cfg = tsfel.get_features_by_domain()
    rows = []
    for domain, features in cfg.items():
        for feature in features.values():
            feature["use"] = "yes"
    cols = tsfel.time_series_features_extractor(cfg, x, fs=100, verbose=0).columns
    first = {}
    for col in cols:
        label = col.split("_", 1)[1]
        base = label.rsplit("_", 1)[0] if label not in first and "_" in label else label
        first.setdefault(base, col)
    names = canonical(first.values(), fs=100)
    domain_of = {f: d for d, fs in cfg.items() for f in fs}
    for (base, col), name in zip(first.items(), names):
        rows.append((domain_of.get(base, ""), base, col, name))
    return sorted(rows)


def main():
    x = np.random.default_rng(0).normal(size=600).cumsum()
    lines = [
        "# Features",
        "",
        "<!-- Generated by scripts/gen_feature_docs.py; edit that, not this. -->",
        "",
        "tsrocket computes every tsfresh and TSFEL feature, checked against both",
        "libraries by the test suite. Give it names in any of three spellings:",
        "",
        "- **tsfresh column names**, exactly as `tsfresh.extract_features` writes them,",
        '  e.g. `value__fft_coefficient__attr_"abs"__coeff_3` (the `value__` kind prefix is optional);',
        "- **TSFEL column names**, e.g. `0_Spectral centroid`, `0_LPCC_3`,",
        "  `0_Wavelet energy_12.5Hz` (frequency labels are resolved with the extractor's `fs`);",
        "- **tsrocket names**, the short canonical form `feature_names` returns,",
        "  e.g. `fft_coeff-3-abs`.",
        "",
        "Parameters other than tsfresh's and TSFEL's defaults work too: change the",
        "number in the name (`fft_coeff-7-angle`, `quantile-0.33`, ...).",
        "",
        "## tsfresh",
        "",
        "One row per calculator; the example is the first column tsfresh's",
        "`ComprehensiveFCParameters` produces for it.",
        "",
        "| Calculator | Example tsfresh column | tsrocket name |",
        "| :--- | :--- | :--- |",
    ]
    for calc, col, name in tsfresh_rows(x):
        lines.append(f"| `{calc}` | `{col}` | `{name}` |")
    lines += [
        "",
        "Not translatable from a tsfresh column name: `matrix_profile` (tsfresh picks",
        "its own window; use `matrix_profile-<window>-<min|max|mean|median|var>`) and",
        "`linear_trend_timewise` (the name lacks the sample period; use",
        "`linear_trend_timewise-<attr>-<seconds per sample>`).",
        "",
        "## TSFEL",
        "",
        "| Domain | Feature | Example TSFEL column | tsrocket name |",
        "| :--- | :--- | :--- | :--- |",
    ]
    for domain, base, col, name in tsfel_rows(x):
        lines.append(f"| {domain} | {base} | `{col}` | `{name}` |")
    lines += [
        "",
        "## tsrocket only",
        "",
        "| Name | What |",
        "| :--- | :--- |",
    ]
    for name, why in NO_REFERENCE.items():
        lines.append(f"| `{name}` | {why} |")
    lines += [
        "",
        "## Meta options",
        "",
        "`fresh-N` in the feature list configures the sliding engine instead of adding a",
        "column: see [sliding-dft-drift.md](sliding-dft-drift.md).",
        "",
    ]
    (ROOT / "docs" / "features.md").write_text("\n".join(lines))


if __name__ == "__main__":
    main()
