use crate::common::ColumnState;

pub struct FeatureContext<'a> {
    pub values: &'a [f32],
    pub running_sorted: Option<&'a [f32]>,
    pub state: &'a mut ColumnState,
    pub n: f32,

    // BaseMetrics
    pub mean: f32,
    pub m2: f32,
    pub m3: f32,
    pub m4: f32,
    pub var: f32,
    pub std_dev: f32,
    pub mac_sum: f32,
    pub mc_sum: f32,

    // SortMetrics
    pub first_max_idx: usize,
    pub last_max_idx: usize,
    pub first_min_idx: usize,
    pub last_min_idx: usize,
    pub median: f32,
    pub median_abs_dev: f32,
    pub iqr: f32,

    // MeanMetrics
    pub mad_sum: f32,
    pub count_a: usize,
    pub count_b: usize,
    pub max_strike_a: usize,
    pub max_strike_b: usize,

    // ZcMetrics
    pub zc_mean: f32,
    pub zc_std: f32,

    // FftResult
    pub freq_centroid: f32,
    pub spectral_decrease: f32,
    pub spectral_slope: f32,
    pub spectral_spread: f32,
    pub spectral_entropy: f32,
    pub spectral_roll_on: f32,
    pub spectral_roll_off: f32,
    pub spectral_skewness: f32,
    pub spectral_kurtosis: f32,
    pub max_frequency: f32,
    pub median_frequency: f32,
    pub fundamental_frequency: f32,
    pub power_bandwidth: f32,
    pub spectral_positive_turning: f32,
    pub spectral_variation: f32,
    pub fft_autocorr: &'a [f32],
    pub fft_complex: &'a [realfft::num_complex::Complex<f32>],
    pub spectrum: &'a [f32],
    /// Length of the series the DFT was taken over (rfft input length).
    pub dft_len: usize,
    pub mfcc: &'a [f32],
    pub lpcc: &'a [f32],
    pub cwt_energy: &'a [f32],
    pub cwt_entropy: f32,
    pub cwt_abs_mean: &'a [f32],
    pub cwt_std: &'a [f32],
    pub cwt_var: &'a [f32],
    pub cwt_peaks: u16,
    pub welch_density: &'a [f32],

    // Complexity Arrays (from engine)
    pub unique_c3_lags: &'a [u16],
    pub unique_tra_lags: &'a [u16],
    pub unique_paa_totals: &'a [u16],
    pub paa_boundaries: &'a [Vec<usize>],
    pub unique_count_above_thresholds: &'a [u32],
    pub unique_count_below_thresholds: &'a [u32],
    pub unique_range_counts: &'a [(u32, u32)],
}

impl<'a> FeatureContext<'a> {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        values: &'a [f32],
        running_sorted: Option<&'a [f32]>,
        state: &'a mut ColumnState,
        n: f32,
        base: crate::metrics::BaseMetrics,
        sort: crate::metrics::SortMetrics,
        mean: crate::metrics::MeanMetrics,
        zc: crate::metrics::ZcMetrics,
        fft: &'a crate::metrics::FftResult,
        unique_c3_lags: &'a [u16],
        unique_tra_lags: &'a [u16],
        unique_paa_totals: &'a [u16],
        paa_boundaries: &'a [Vec<usize>],
        unique_count_above_thresholds: &'a [u32],
        unique_count_below_thresholds: &'a [u32],
        unique_range_counts: &'a [(u32, u32)],
    ) -> Self {
        state.reset_window_caches();
        Self {
            values,
            running_sorted,
            n,
            mean: base.mean,
            m2: base.m2,
            m3: base.m3,
            m4: base.m4,
            var: base.var,
            std_dev: base.std_dev,
            mac_sum: state.mac_sum,
            mc_sum: state.mc_sum,
            first_max_idx: sort.first_max_idx,
            last_max_idx: sort.last_max_idx,
            first_min_idx: sort.first_min_idx,
            last_min_idx: sort.last_min_idx,
            median: sort.median,
            median_abs_dev: sort.median_abs_dev,
            iqr: sort.iqr,
            mad_sum: mean.mad_sum,
            count_a: mean.count_a,
            count_b: mean.count_b,
            max_strike_a: mean.max_strike_a,
            max_strike_b: mean.max_strike_b,
            zc_mean: zc.zc_mean,
            zc_std: zc.zc_std,
            freq_centroid: fft.freq_centroid,
            spectral_decrease: fft.spectral_decrease,
            spectral_slope: fft.spectral_slope,
            spectral_spread: fft.spectral_spread,
            spectral_entropy: fft.spectral_entropy,
            spectral_roll_on: fft.spectral_roll_on,
            spectral_roll_off: fft.spectral_roll_off,
            spectral_skewness: fft.spectral_skewness,
            spectral_kurtosis: fft.spectral_kurtosis,
            max_frequency: fft.max_frequency,
            median_frequency: fft.median_frequency,
            fundamental_frequency: fft.fundamental_frequency,
            power_bandwidth: fft.power_bandwidth,
            spectral_positive_turning: fft.spectral_positive_turning,
            spectral_variation: fft.spectral_variation,
            fft_autocorr: &fft.fft_autocorr,
            mfcc: &fft.mfcc,
            lpcc: &fft.lpcc,
            cwt_energy: &fft.cwt_energy,
            cwt_entropy: fft.cwt_entropy,
            cwt_abs_mean: &fft.cwt_abs_mean,
            cwt_std: &fft.cwt_std,
            cwt_var: &fft.cwt_var,
            fft_complex: &fft.fft_complex,
            spectrum: &fft.spectrum,
            dft_len: fft.dft_len,
            cwt_peaks: fft.cwt_peaks,
            welch_density: &fft.welch_density,

            unique_c3_lags,
            unique_tra_lags,
            unique_paa_totals,
            paa_boundaries,
            unique_count_above_thresholds,
            unique_count_below_thresholds,
            unique_range_counts,
            state,
        }
    }
}
